'use strict'
module.exports = {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  ADD_PROJECTS: 'ADD_PROJECTS',
  DELETE_PROJECTS: 'DELETE_PROJECTS',
  ADD_FUNCTION_TO_PROJECT: 'ADD_FUNCTION_TO_PROJECT',
}
